const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch({ headless: true });
  const p = await b.newPage();
  await p.goto('https://sampleapp.tricentis.com/101/app.php');
  await p.getByRole('link', { name: 'Automobile' }).click();
  await p.locator('#make').selectOption('Toyota');
  await p.locator('#engineperformance').fill('120');
  await p.getByRole('textbox', { name: 'MM/DD/YYYY' }).fill('01/15/2020');
  await p.locator('#numberofseats').selectOption('5');
  await p.locator('#fuel').selectOption('Petrol');
  await p.locator('#listprice').fill('25000');
  await p.locator('#licenseplatenumber').fill('DEV69');
  await p.locator('#annualmileage').fill('12000');
  await p.getByRole('button', { name: 'Next' }).click();
  await p.waitForTimeout(2000);
  await p.locator('#firstname').fill('John');
  await p.locator('#lastname').fill('Doe');
  await p.locator('#birthdate').fill('01/01/1990');
  await p.evaluate(() => { const r = document.getElementById('gendermale'); if (r) r.click(); });
  await p.locator('#streetaddress').fill('221B Baker Street');
  await p.locator('#country').selectOption({ label: 'India' });
  await p.locator('#zipcode').fill('560001');
  await p.locator('#city').fill('Bengaluru');
  await p.locator('#occupation').selectOption('Employee');
  await p.locator('#nextenterproductdata').click();
  await p.waitForTimeout(3000);
  const o1 = await p.locator('#insurancesum option').allTextContents();
  console.log('insurancesum:', JSON.stringify(o1));
  const o2 = await p.locator('#meritrating option').allTextContents();
  console.log('meritrating:', JSON.stringify(o2));
  const o3 = await p.locator('#damageinurance option').allTextContents();
  console.log('damageinurance:', JSON.stringify(o3));
  await b.close();
    const o4 = await p.locator('#damageinsurance option').allTextContents();
    console.log('damageinsurance:', JSON.stringify(o4));
    const o5 = await p.locator('#courtesycar option').allTextContents();
    console.log('courtesycar:', JSON.stringify(o5));
    const allSelects = await p.evaluate(() => {
      return Array.from(document.querySelectorAll('select')).map(s => ({ id: s.id, name: s.name, options: Array.from(s.options).map(o => o.text) }));
    });
    console.log('all selects on tab3:', JSON.stringify(allSelects, null, 2));
    await b.close();
    const o4 = await p.locator('#damageinsurance option').allTextContents();
    console.log('damageinsurance:', JSON.stringify(o4));
    const o5 = await p.locator('#courtesycar option').allTextContents();
    console.log('courtesycar:', JSON.stringify(o5));
    const allSelects = await p.evaluate(() => {
      return Array.from(document.querySelectorAll('select')).map(s => ({ id: s.id, name: s.name, options: Array.from(s.options).map(o => o.text) }));
    });
    console.log('all selects on tab3:', JSON.stringify(allSelects, null, 2));
    await b.close();
})();
